//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.16 at 03:37:07 PM CDT 
//


package org.example.skills;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for battingSkill complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="battingSkill">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/skills}skill">
 *       &lt;sequence>
 *         &lt;element name="battingAvg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ballsFaced" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "battingSkill", propOrder = {
    "battingAvg",
    "ballsFaced"
})
public class BattingSkill
    extends Skill
{

    protected String battingAvg;
    protected String ballsFaced;

    /**
     * Gets the value of the battingAvg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBattingAvg() {
        return battingAvg;
    }

    /**
     * Sets the value of the battingAvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBattingAvg(String value) {
        this.battingAvg = value;
    }

    /**
     * Gets the value of the ballsFaced property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBallsFaced() {
        return ballsFaced;
    }

    /**
     * Sets the value of the ballsFaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBallsFaced(String value) {
        this.ballsFaced = value;
    }

}
